export const demoC = [
  { short: 'AF', name: 'AFGHANISTAN' },
  { short: 'AL', name: 'ALBANIA' },
  { short: 'DZ', name: 'ALGERIA' },
  { short: 'AS', name: 'AMERICAN SAMOA' },
  { short: 'AD', name: 'ANDORRA' },
  { short: 'AO', name: 'ANGOLA' },
  { short: 'AI', name: 'ANGUILLA' },
  { short: 'AQ', name: 'ANTARCTICA' },
  { short: 'AG', name: 'ANTIGUA AND BARBUDA' },
  { short: 'AR', name: 'ARGENTINA' },
  { short: 'AM', name: 'ARMENIA' },
  { short: 'AW', name: 'ARUBA' },
  { short: 'AU', name: 'AUSTRALIA' },
  { short: 'AT', name: 'AUSTRIA' },
  { short: 'AZ', name: 'AZERBAIJAN' },
  { short: 'BS', name: 'BAHAMAS' },
  { short: 'BH', name: 'BAHRAIN' },
  { short: 'BD', name: 'BANGLADESH' },
  { short: 'BB', name: 'BARBADOS' },
  { short: 'BY', name: 'BELARUS' },
  { short: 'BE', name: 'BELGIUM' },
  { short: 'BZ', name: 'BELIZE' },
  { short: 'BJ', name: 'BENIN' },
  { short: 'BM', name: 'BERMUDA' },
  { short: 'BT', name: 'BHUTAN' },
  { short: 'BO', name: 'BOLIVIA' },
  { short: 'BA', name: 'BOSNIA AND HERZEGOVINA' },
  { short: 'BW', name: 'BOTSWANA' },
  { short: 'BV', name: 'BOUVET ISLAND' },
  { short: 'BR', name: 'BRAZIL' },
  { short: 'IO', name: 'BRITISH INDIAN OCEAN TERRITORY' },
  { short: 'BN', name: 'BRUNEI DARUSSALAM' },
  { short: 'BG', name: 'BULGARIA' },
  { short: 'BF', name: 'BURKINA FASO' },
  { short: 'BI', name: 'BURUNDI' },
  { short: 'KH', name: 'CAMBODIA' },
  { short: 'CM', name: 'CAMEROON' },
  { short: 'CA', name: 'CANADA' },
  { short: 'CV', name: 'CAPE VERDE' },
  { short: 'KY', name: 'CAYMAN ISLANDS' },
  { short: 'CF', name: 'CENTRAL AFRICAN REPUBLIC' },
  { short: 'TD', name: 'CHAD' },
  { short: 'CL', name: 'CHILE' },
  { short: 'CN', name: 'CHINA' },
  { short: 'CX', name: 'CHRISTMAS ISLAND' },
  { short: 'CC', name: 'COCOS (KEELING) ISLANDS' },
  { short: 'CO', name: 'COLOMBIA' },
  { short: 'KM', name: 'COMOROS' },
  { short: 'CG', name: 'CONGO' },
  { short: 'CD', name: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE' },
  { short: 'CK', name: 'COOK ISLANDS' },
  { short: 'CR', name: 'COSTA RICA' },
  { short: 'CI', name: 'COTE D IVOIRE' },
  { short: 'HR', name: 'CROATIA' },
  { short: 'CU', name: 'CUBA' },
  { short: 'CY', name: 'CYPRUS' },
  { short: 'CZ', name: 'CZECH REPUBLIC' },
  { short: 'DK', name: 'DENMARK' },
  { short: 'DJ', name: 'DJIBOUTI' },
  { short: 'DM', name: 'DOMINICA' },
  { short: 'DO', name: 'DOMINICAN REPUBLIC' },
  { short: 'TP', name: 'EAST TIMOR' },
  { short: 'EC', name: 'ECUADOR' },
  { short: 'EG', name: 'EGYPT' },
  { short: 'SV', name: 'EL SALVADOR' },
  { short: 'GQ', name: 'EQUATORIAL GUINEA' },
  { short: 'ER', name: 'ERITREA' },
  { short: 'EE', name: 'ESTONIA' },
  { short: 'ET', name: 'ETHIOPIA' },
  { short: 'FK', name: 'FALKLAND ISLANDS (MALVINAS)' },
  { short: 'FO', name: 'FAROE ISLANDS' },
  { short: 'FJ', name: 'FIJI' },
  { short: 'FI', name: 'FINLAND' },
  { short: 'FR', name: 'FRANCE' },
  { short: 'GF', name: 'FRENCH GUIANA' },
  { short: 'PF', name: 'FRENCH POLYNESIA' },
  { short: 'TF', name: 'FRENCH SOUTHERN TERRITORIES' },
  { short: 'GA', name: 'GABON' },
  { short: 'GM', name: 'GAMBIA' },
  { short: 'GE', name: 'GEORGIA' },
  { short: 'DE', name: 'GERMANY' },
  { short: 'GH', name: 'GHANA' },
  { short: 'GI', name: 'GIBRALTAR' },
  { short: 'GR', name: 'GREECE' },
  { short: 'GL', name: 'GREENLAND' },
  { short: 'GD', name: 'GRENADA' },
  { short: 'GP', name: 'GUADELOUPE' },
  { short: 'GU', name: 'GUAM' },
  { short: 'GT', name: 'GUATEMALA' },
  { short: 'GN', name: 'GUINEA' },
  { short: 'GW', name: 'GUINEA-BISSAU' },
  { short: 'GY', name: 'GUYANA' },
  { short: 'HT', name: 'HAITI' },
  { short: 'HM', name: 'HEARD ISLAND AND MCDONALD ISLANDS' },
  { short: 'VA', name: 'HOLY SEE (VATICAN CITY STATE)' },
  { short: 'HN', name: 'HONDURAS' },
  { short: 'HK', name: 'HONG KONG' },
  { short: 'HU', name: 'HUNGARY' },
  { short: 'IS', name: 'ICELAND' },
  { short: 'IN', name: 'INDIA' },
  { short: 'ID', name: 'INDONESIA' },
  { short: 'IR', name: 'IRAN, ISLAMIC REPUBLIC OF' },
  { short: 'IQ', name: 'IRAQ' },
  { short: 'IE', name: 'IRELAND' },
  { short: 'IL', name: 'ISRAEL' },
  { short: 'IT', name: 'ITALY' },
  { short: 'JM', name: 'JAMAICA' },
  { short: 'JP', name: 'JAPAN' },
  { short: 'JO', name: 'JORDAN' },
  { short: 'KZ', name: 'KAZAKSTAN' },
  { short: 'KE', name: 'KENYA' },
  { short: 'KI', name: 'KIRIBATI' },
  { short: 'KP', name: 'KOREA DEMOCRATIC PEOPLES REPUBLIC OF' },
  { short: 'KR', name: 'KOREA REPUBLIC OF' },
  { short: 'KW', name: 'KUWAIT' },
  { short: 'KG', name: 'KYRGYZSTAN' },
  { short: 'LA', name: 'LAO PEOPLES DEMOCRATIC REPUBLIC' },
  { short: 'LV', name: 'LATVIA' },
  { short: 'LB', name: 'LEBANON' },
  { short: 'LS', name: 'LESOTHO' },
  { short: 'LR', name: 'LIBERIA' },
  { short: 'LY', name: 'LIBYAN ARAB JAMAHIRIYA' },
  { short: 'LI', name: 'LIECHTENSTEIN' },
  { short: 'LT', name: 'LITHUANIA' },
  { short: 'LU', name: 'LUXEMBOURG' },
  { short: 'MO', name: 'MACAU' },
  { short: 'MK', name: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF' },
  { short: 'MG', name: 'MADAGASCAR' },
  { short: 'MW', name: 'MALAWI' },
  { short: 'MY', name: 'MALAYSIA' },
  { short: 'MV', name: 'MALDIVES' },
  { short: 'ML', name: 'MALI' },
  { short: 'MT', name: 'MALTA' },
  { short: 'MH', name: 'MARSHALL ISLANDS' },
  { short: 'MQ', name: 'MARTINIQUE' },
  { short: 'MR', name: 'MAURITANIA' },
  { short: 'MU', name: 'MAURITIUS' },
  { short: 'YT', name: 'MAYOTTE' },
  { short: 'MX', name: 'MEXICO' },
  { short: 'FM', name: 'MICRONESIA, FEDERATED STATES OF' },
  { short: 'MD', name: 'MOLDOVA, REPUBLIC OF' },
  { short: 'MC', name: 'MONACO' },
  { short: 'MN', name: 'MONGOLIA' },
  { short: 'MS', name: 'MONTSERRAT' },
  { short: 'MA', name: 'MOROCCO' },
  { short: 'MZ', name: 'MOZAMBIQUE' },
  { short: 'MM', name: 'MYANMAR' },
  { short: 'NA', name: 'NAMIBIA' },
  { short: 'NR', name: 'NAURU' },
  { short: 'NP', name: 'NEPAL' },
  { short: 'NL', name: 'NETHERLANDS' },
  { short: 'AN', name: 'NETHERLANDS ANTILLES' },
  { short: 'NC', name: 'NEW CALEDONIA' },
  { short: 'NZ', name: 'NEW ZEALAND' },
  { short: 'NI', name: 'NICARAGUA' },
  { short: 'NE', name: 'NIGER' },
  { short: 'NG', name: 'NIGERIA' },
  { short: 'NU', name: 'NIUE' },
  { short: 'NF', name: 'NORFOLK ISLAND' },
  { short: 'MP', name: 'NORTHERN MARIANA ISLANDS' },
  { short: 'NO', name: 'NORWAY' },
  { short: 'OM', name: 'OMAN' },
  { short: 'PK', name: 'PAKISTAN' },
  { short: 'PW', name: 'PALAU' },
  { short: 'PS', name: 'PALESTINIAN TERRITORY, OCCUPIED' },
  { short: 'PA', name: 'PANAMA' },
  { short: 'PG', name: 'PAPUA NEW GUINEA' },
  { short: 'PY', name: 'PARAGUAY' },
  { short: 'PE', name: 'PERU' },
  { short: 'PH', name: 'PHILIPPINES' },
  { short: 'PN', name: 'PITCAIRN' },
  { short: 'PL', name: 'POLAND' },
  { short: 'PT', name: 'PORTUGAL' },
  { short: 'PR', name: 'PUERTO RICO' },
  { short: 'QA', name: 'QATAR' },
  { short: 'RE', name: 'REUNION' },
  { short: 'RO', name: 'ROMANIA' },
  { short: 'RU', name: 'RUSSIAN FEDERATION' },
  { short: 'RW', name: 'RWANDA' },
  { short: 'SH', name: 'SAINT HELENA' },
  { short: 'KN', name: 'SAINT KITTS AND NEVIS' },
  { short: 'LC', name: 'SAINT LUCIA' },
  { short: 'PM', name: 'SAINT PIERRE AND MIQUELON' },
  { short: 'VC', name: 'SAINT VINCENT AND THE GRENADINES' },
  { short: 'WS', name: 'SAMOA' },
  { short: 'SM', name: 'SAN MARINO' },
  { short: 'ST', name: 'SAO TOME AND PRINCIPE' },
  { short: 'SA', name: 'SAUDI ARABIA' },
  { short: 'SN', name: 'SENEGAL' },
  { short: 'SC', name: 'SEYCHELLES' },
  { short: 'SL', name: 'SIERRA LEONE' },
  { short: 'SG', name: 'SINGAPORE' },
  { short: 'SK', name: 'SLOVAKIA' },
  { short: 'SI', name: 'SLOVENIA' },
  { short: 'SB', name: 'SOLOMON ISLANDS' },
  { short: 'SO', name: 'SOMALIA' },
  { short: 'ZA', name: 'SOUTH AFRICA' },
  { short: 'GS', name: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS' },
  { short: 'ES', name: 'SPAIN' },
  { short: 'LK', name: 'SRI LANKA' },
  { short: 'SD', name: 'SUDAN' },
  { short: 'SR', name: 'SURINAME' },
  { short: 'SJ', name: 'SVALBARD AND JAN MAYEN' },
  { short: 'SZ', name: 'SWAZILAND' },
  { short: 'SE', name: 'SWEDEN' },
  { short: 'CH', name: 'SWITZERLAND' },
  { short: 'SY', name: 'SYRIAN ARAB REPUBLIC' },
  { short: 'TW', name: 'TAIWAN, PROVINCE OF CHINA' },
  { short: 'TJ', name: 'TAJIKISTAN' },
  { short: 'TZ', name: 'TANZANIA, UNITED REPUBLIC OF' },
  { short: 'TH', name: 'THAILAND' },
  { short: 'TG', name: 'TOGO' },
  { short: 'TK', name: 'TOKELAU' },
  { short: 'TO', name: 'TONGA' },
  { short: 'TT', name: 'TRINIDAD AND TOBAGO' },
  { short: 'TN', name: 'TUNISIA' },
  { short: 'TR', name: 'TURKEY' },
  { short: 'TM', name: 'TURKMENISTAN' },
  { short: 'TC', name: 'TURKS AND CAICOS ISLANDS' },
  { short: 'TV', name: 'TUVALU' },
  { short: 'UG', name: 'UGANDA' },
  { short: 'UA', name: 'UKRAINE' },
  { short: 'AE', name: 'UNITED ARAB EMIRATES' },
  { short: 'GB', name: 'UNITED KINGDOM' },
  { short: 'US', name: 'UNITED STATES' },
  { short: 'UM', name: 'UNITED STATES MINOR OUTLYING ISLANDS' },
  { short: 'UY', name: 'URUGUAY' },
  { short: 'UZ', name: 'UZBEKISTAN' },
  { short: 'VU', name: 'VANUATU' },
  { short: 'VE', name: 'VENEZUELA' },
  { short: 'VN', name: 'VIET NAM' },
  { short: 'VG', name: 'VIRGIN ISLANDS, BRITISH' },
  { short: 'VI', name: 'VIRGIN ISLANDS, U.S.' },
  { short: 'WF', name: 'WALLIS AND FUTUNA' },
  { short: 'EH', name: 'WESTERN SAHARA' },
  { short: 'YE', name: 'YEMEN' },
  { short: 'YU', name: 'YUGOSLAVIA' },
  { short: 'ZM', name: 'ZAMBIA' },
  { short: 'ZW', name: 'ZIMBABWE' },
];
